scrape_configs:

  ## gather metrics of prometheus itself
- job_name: prometheus
  static_configs:
    - targets:
      - localhost:9090

  ## gather the metrics of json_exporter application itself
- job_name: json_exporter
  static_configs:
    - targets:
      - localhost:7979 ## Location of the json exporter's real <hostname>:<port>

  ## gather the metrics from third party json sources, via the json exporter
- job_name: json
  metrics_path: /probe
  static_configs:
    - targets:
      - http://host-1.foobar.com/dummy/data.json
      - http://host-2:8000/other-examples/data.json
      - http://localhost:8000/examples/data.json ## Used from the example steps in Readme
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: localhost:7979 ## Location of the json exporter's real <hostname>:<port>

